apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: my-cluster
  namespace: search-indexing-svc
spec:
  general:
    version: 1.2.4
    httpPort: 9200
    vendor: opensearch
    version: latest
    serviceName: my-cluster
  dashboards:
    version: 1.2.0
    enable: true
    replicas: 2
    resources:
      limits:
         memory: "1Gi"
         cpu: "500m"
  confMgmt:
    smartScaler: true
  nodePools:
    - component: masters
      replicas: 3
      diskSize: "30Gi"
      NodeSelector:
      resources:
         limits:
            memory: "2Gi"
            cpu: 1
      roles:
        - "master"
    - component: nodes
      replicas: 3
      diskSize: "100Gi"
      NodeSelector:
      resources:
         limits:
            memory: "2Gi"
            cpu: 1
      roles:
        - "data"
        - "ingest"
