nodeSelector: {}
manager:
  tolerations: []
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  image:
    repository: public.ecr.aws/opsterio/opensearch-operator
    tag: latest
