nodeSelector: {}
tolerations: []
manager:
  resources:
    limits:
      cpu: 2
      memory: 1Gi
    requests:
      cpu: 2
      memory: 1Gi
  image:
    repository: public.ecr.aws/opsterio/opensearch-operator
    ## tag: v2.0
    tag: v2.0
    pullPolicy: "Always"
  # If a watchNamespace is specified, the manager's cache will be restricted to
  # watch objects in the desired namespace. Defaults is to watch all namespaces.
  watchNamespace:
